"use client"

import { useState } from "react"
import { ChevronDown, ChevronUp } from "lucide-react"

export default function FAQPage() {
  const [openIndex, setOpenIndex] = useState<number | null>(0)

  const faqs = [
    {
      question: "What are Lucky Products?",
      answer: `Lucky products and luxury items aren't just about style, they represent the highest level of design, high-end and uniqueness that can offer by a company. Even though most people can't afford them, EarningHub is a platform for many luxury products like Gucci, Louis Vuitton, Glossier, Rolex & Tiffany etc. to showcase advanced model, comfort, and brand prestige.

Along with these luxury items, each piece is a testament to long-lasting elegance, and masterful craftsmanship. These are made from top-quality and rare materials to ensure lifestyle essentials and elegance. While expensive, they help maintain the luxury feel of the way of lifestyle and allow new luxury brands to eventually reach more affordable items.`
    },
    {
      question: "What is a Lucky Order Evaluation?",
      answer: `Lucky products are high-value items with limited availability, and each member has a chance to receive 0 to 2 of them in a single round. These are randomly generated by the system and offer 6 times the regular commission, along with lucky order bonuses.

The evaluation of Lucky products are based on the member's current account balance, which means the required evaluation may vary. Due to the high rewards, the chances of receiving a Lucky order are low. If selected, you must contact on-duty customer service to proceed and claim your rewards.`
    },
    {
      question: "What is a Top-Grade Order Evaluation?",
      answer: `Top-grade products are exclusive benefits offered by the platform to reward and motivate high-level members. These products are extremely rare, with a very low chance of being assigned.

To promote them, eligible members receive 8 times the regular commission, along with the highest bonus percentage available for products. Only members who have reached premium level are eligible to claim these high-value products and enjoy their associated rewards.`
    }
  ]

  const toggleFAQ = (index: number) => {
    setOpenIndex(openIndex === index ? null : index)
  }

  return (
    <div className="min-h-screen bg-gray-50 py-12 px-4 md:px-8">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="text-center mb-12">
          <h1 className="text-4xl md:text-5xl font-bold text-gray-900 mb-4">
            Frequently Asked Questions
          </h1>
          <p className="text-lg text-gray-600">
            Find answers to common questions about our platform and services
          </p>
        </div>

        {/* FAQ Accordion */}
        <div className="space-y-4">
          {faqs.map((faq, index) => (
            <div
              key={index}
              className="bg-white rounded-lg border-2 border-gray-200 overflow-hidden transition-all duration-300 hover:shadow-lg"
            >
              {/* Question */}
              <button
                onClick={() => toggleFAQ(index)}
                className={`w-full px-6 py-5 flex items-center justify-between text-left transition-all duration-300 ${
                  openIndex === index
                    ? "bg-green-50 border-b-2 border-green-200"
                    : "hover:bg-gray-50"
                }`}
              >
                <h3
                  className={`text-lg md:text-xl font-bold pr-4 transition-colors duration-300 ${
                    openIndex === index ? "text-green-700" : "text-gray-900"
                  }`}
                >
                  {faq.question}
                </h3>
                <div
                  className={`flex-shrink-0 w-8 h-8 rounded-full flex items-center justify-center transition-all duration-300 ${
                    openIndex === index
                      ? "bg-green-600 text-white"
                      : "bg-gray-200 text-gray-600"
                  }`}
                >
                  {openIndex === index ? (
                    <ChevronUp className="w-5 h-5" />
                  ) : (
                    <ChevronDown className="w-5 h-5" />
                  )}
                </div>
              </button>

              {/* Answer */}
              <div
                className={`transition-all duration-500 ease-in-out ${
                  openIndex === index
                    ? "max-h-[1000px] opacity-100"
                    : "max-h-0 opacity-0"
                }`}
              >
                <div className="px-6 py-6 bg-white">
                  <div className="prose prose-sm md:prose-base max-w-none">
                    {faq.answer.split('\n\n').map((paragraph, pIndex) => (
                      <p key={pIndex} className="text-gray-700 leading-relaxed mb-4 last:mb-0">
                        {paragraph}
                      </p>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Back Button */}
        <div className="mt-8 text-center">
          <a
            href="/"
            className="inline-block bg-gray-800 hover:bg-gray-900 text-white font-semibold px-6 py-3 rounded-lg transition-all duration-300 hover:scale-105"
          >
            Back to Home
          </a>
        </div>
      </div>
    </div>
  )
}
